apiVersion: v1
kind: Service
metadata:
   name: tomcat-service
   labels:
     name: tomcat1pod-service
spec:
   type: NodePort
   ports:
     - port: 80
       targetPort: 8080
       nodePort: 31516
   selector:
     name: tomcat1pod